levels = [{"map": ["WWWWWWWWWWWWWWWWWWWW",
                   "W          1       W",
                   "W         WWWWWW   W",
                   "W   WWWW       W   W",
                   "W   W        WWWW  W",
                   "W WWW  WWWW        W",
                   "W   W     W W   P   W",
                   "W   W     W   WWW  W",
                   "W   WWW WWW   W W  W",
                   "W     W   W   W W  W",
                   "WWW   W   WWWWW W  W",
                   "W W      WW        W",
                   "W W   WWWW   WWW   W",
                   "W     W    E   W             2         ",
                   "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", ],
           "monsters": {"1": {"len": 10, "image": "goldappl.png"}, "2": {"len": 2, "image": "goldappl.png"}},
           "next_level_id": 1},
          {"map": ["WWWWWWWWWWWWWWWWWWWW",
                   "W          1       W",
                   "W         WWWWWW   W",
                   "W   WWWW       W   W",
                   "W   W     P  WWWW  W",
                   "W WWW  WWWW        W",
                   "W   W     W W      W",
                   "W   W     W   WWW  W",
                   "W   WWW WWW   W W  W",
                   "W     W   W   W W  W",
                   "WWW   W   WWWWW W  W",
                   "W W      WW        W",
                   "W W   WWWW   WWW   W",
                   "W     W    E   W             2         ",
                   "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", ],
           "monsters": {"1": {"len": 10, "image": "goldappl.png"}, "2": {"len": 2, "image": "goldappl.png"}},
           "next_level_id": 0}
          ]
